### ISSUE TITLE
pod required?

### ISSUE THREAD

**Issue by whiteyhat** [blockstack/blockstack-react-native#11] opened 2019-05-24 12:44 UTC
Hey! I am currently using `expo` for the react native development. Is it required to install the pods in order to implement the blockstack SDK?

**Comment by moxiegirl** [comment] 2019-05-24 14:52
@whiteyhat thanks for the issue. Our tutorial code uses the pods. @shreyasthiagaraj perhaps tried that out and can answer your question.

**Comment by whiteyhat** [comment] 2019-05-24 15:09
Cool! I’m having such a hard time trying to compile the SDK using explo cli

**Comment by shreyasthiagaraj** [comment] 2019-05-24 15:36
Hey, I haven't tried using expo, but the recommended way to implement the SDK is via cocoapods. What errors are you getting? And I'm assuming by "pods" you're referring to these, I assume:

```
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge', # Include this for RN >= 0.47
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # Needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

The Blockstack pod is definitely needed.

**Comment by whiteyhat** [comment] 2019-05-24 15:42
https://github.com/blockstack/blockstack-react-native/issues/12

**Comment by shreyasthiagaraj** [comment] 2019-05-24 15:44
@whiteyhat I think I know what the issue is, and it may be solved with a new release of the Blockstack iOS SDK. Let me do that now and get back to you, just hang on for a bit--apologies for the issue!

**Comment by whiteyhat** [comment] 2019-05-25 00:51
Okay, please reply to me as soon is fixed pls

**Comment by shreyasthiagaraj** [comment] 2019-05-25 10:30
Closing this as it is essentially a duplicate of #12. Please continue the discussion there.

**Closed by shreyasthiagaraj** 2019-05-25 10:30 UTC
