### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by whiteyhat** [blockstack/blockstack-react-native#12] opened 2019-05-24 13:10 UTC
<img width="373" alt="Screenshot 2019-05-24 at 14 10 00" src="https://user-images.githubusercontent.com/31220861/58329932-b366d600-7e2d-11e9-9a90-a869c6767028.png">

**Comment by shreyasthiagaraj** [comment] 2019-05-25 10:29
@whiteyhat The issue is that the swift module is not being properly imported. This seems to be a result of changes in XCode 10.2, as discussed here: https://github.com/facebook/react-native/issues/24139

Still working on a fix, will keep you updated.

**Comment by whiteyhat** [comment] 2019-05-25 11:16
Since the Blockstack can't be evil hackathon was giving voucher if the hackathon app was uploaded before the 25th, and as the minimum requirement, it should as support blockstack auth. But as described above, the SDK itself has compiling issues.

What can I do to still being eligible if this does not depend on me?

**Comment by shreyasthiagaraj** [comment] 2019-05-25 11:37
@whiteyhat This will hopefully be fixed within the day, so it should not be blocker for your entry. In the mean time, you can use the iOS 12.1 simulator instead of 12.2. This should make things work immediately.

A more permanent fix will come as part of react-native v0.60.0 (relevant commit: https://github.com/facebook/react-native/commit/ff66600224e78fec5d0e902f8a035b78ed31a961). I'm now attempting to configure npm to use the `0.60-stable` branch directly from github for the react-native dependency, once I get this working the issue should be resolved.

**Comment by whiteyhat** [comment] 2019-05-26 11:51
Nice, ping me back when that is done so I can implement blockstack auth seamlessly

**Comment by shreyasthiagaraj** [comment] 2019-05-26 11:55
I hit a snag yesterday—once I got it using branch ‘0.60-stable’ I found that they have changed how the subspecs are defined and imported, causing errors when doing pod install. Still figuring out how to import those subspecs (i.e. RCTWebSocket, etc.). I’ll ping you as soon as the fix is ready!

Again if you wish to be unblocked immediately add the iOS 12.1 simulator in XCode. Thanks and hang on 😄.

**Comment by whiteyhat** [comment] 2019-05-26 14:52
Okay, but this will affect when creating the IPA? (to upload the final version in the app store)

**Comment by shreyasthiagaraj** [comment] 2019-05-26 18:32
No, I don't believe it will. But by the time you submit the final version I'd expect react-native to be properly updated.

**Comment by whiteyhat** [comment] 2019-05-26 19:19
Yeah, but it is quite complicated.. since I am using `expo-cli` I am not using an external simulator. So I need to be constantly building the iOS app to compile the blockstack auth... and that is a bit of a pitty

**Comment by whiteyhat** [comment] 2019-05-26 20:40
It does not work on the iOS 12.1 simulator either...
<img width="409" alt="Screenshot 2019-05-26 at 21 39 49" src="https://user-images.githubusercontent.com/31220861/58386953-ead8ac80-7ffe-11e9-96e8-9216614b79a8.png">

**Comment by shreyasthiagaraj** [comment] 2019-05-26 23:21
Hey--can you expand and screenshot the error you are getting using iOS 12.1?

**Comment by whiteyhat** [comment] 2019-05-27 00:07
<img width="417" alt="Screenshot 2019-05-27 at 01 07 03" src="https://user-images.githubusercontent.com/31220861/58388844-d22abf80-801b-11e9-8837-d8b13a4e894d.png">
<img width="427" alt="Screenshot 2019-05-27 at 01 06 47" src="https://user-images.githubusercontent.com/31220861/58388845-d22abf80-801b-11e9-81b7-5c9d25b6352c.png">

**Comment by shreyasthiagaraj** [comment] 2019-05-27 10:30
Hey, I'm trying out Expo-cli. Are you on our slack (https://community.blockstack.org/slack)? Would be faster to message you on there. Thanks!

**Comment by whiteyhat** [comment] 2019-05-27 12:26
Sure! I am not, but I can log in

**Comment by shreyasthiagaraj** [comment] 2019-05-27 21:35
@whiteyhat Whew, FINALLY managed to track down and fix the issue. Two ways to get a working version:

1. Easiest way to fix:
Reclone the repository (not sure if pulling the latest changes will fix it for you, but you can try first).

2. Alternative way to fix if you don't want to re-download the repo:
a. Pull latest code in `develop` branch.
b. In XCode, delete the blue `RNBlockstackSdk` folder and select "Remove References".
c. Re-add that same folder from "example/node_modules/react-native-blockstack/ios/", but make sure "Create Groups" is selected in the file picker window that pops up.
d. The `RNBlockstackSdk` folder should be back now, but this time in yellow 😯.

That's it! Should be working. At some point it seems react native broke for what appears as "blue folders" in XCode. The blue folder represents folders in the deployed app bundle, and apparently RN related code within them stops working. By doing the fix outlined above, we are turning it into a yellow folder which means that it will _not_ be in its own folder in the app bundle.

The other issue I mentioned above resulted in the same error, but for a different reason, and so fixing that did not actually fix this issue. Sorry for the wait :).

**Comment by whiteyhat** [comment] 2019-05-27 21:42
If I go for the 1st one (the easiest way to fix). When I clone it, I had to change to the develop branch?

**Comment by shreyasthiagaraj** [comment] 2019-05-27 21:45
Just merged everything into master branch, so either `develop` or `master` will work :).

**Comment by whiteyhat** [comment] 2019-05-27 22:06
Nice. Does it have to be `12.1` or it alos works on `12.2`?

**Comment by shreyasthiagaraj** [comment] 2019-05-27 22:06
Works on 12.2 as well

**Comment by whiteyhat** [comment] 2019-05-27 22:07
👍

**Comment by whiteyhat** [comment] 2019-05-27 22:40
Okay, It works. Even tho, it has some compiling issues. I am not sure how this will affect 
<img width="914" alt="Screenshot 2019-05-27 at 23 40 05" src="https://user-images.githubusercontent.com/31220861/58441300-dcf75a00-80d8-11e9-9010-871401b686c3.png">
the upload of the IPA to the App Store

**Comment by shreyasthiagaraj** [comment] 2019-05-27 22:47
That is probably a local issue. Try running your commands with `sudo`. Other who have had this error seem to have fixed it by reinstalling things (https://github.com/facebook/create-react-app/issues/4316).

**Closed** 2019-05-27 22:48 UTC
